dist: xenial

os:
    - linux
#    - osx 
#    - windows

env:
    global:
        - BLENDER_CACHE=$HOME/.cache/blender
        - BL_ADDON=fake_addon
    matrix:
        - BLENDER_VERSION="2.91"
        - BLENDER_VERSION="2.90"
        - BLENDER_VERSION="2.83"
        - BLENDER_VERSION="2.82"
        - BLENDER_VERSION="2.81"
        - BLENDER_VERSION="2.80"
        - BLENDER_VERSION="2.79"

language: python
python:
    - 3.7

cache:
    apt: true
    directories:
        - $HOME/.cache/pip
        - ${BLENDER_CACHE}

addons:
    apt:
        packages:
            - blender

before_install:
    - mkdir -p ${BLENDER_CACHE}
    - ls ${BLENDER_CACHE}

install:
    - cd $TRAVIS_BUILD_DIR
    - python3 --version
    - pip install -r blender_requirements.txt
    - pip list

script:
    - cd ${TRAVIS_BUILD_DIR}
    #- make flake8
    - python3 ${TRAVIS_BUILD_DIR}/scripts/test_addon.py ${BL_ADDON} ${BLENDER_VERSION}
    
after_success:
    - bash <(curl -s https://codecov.io/bash)

notifications:
    email:
        on_success: change
        on_failure: always
